// Screen 7: Complete / End Actions
// END MOMENT of Peak-End Rule - Satisfying conclusion with clear actions
// Allows download, restart, or additional actions

import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import Button from '../components/Button';
import useAppStore from '../store/appStore';

export default function Complete() {
  const navigate = useNavigate();
  const {
    selectedPlant,
    municipality,
    recommendations,
    recommendationSummary,
    soilData,
    resetApp
  } = useAppStore();

  const handleDownloadPDF = () => {
    // In a real implementation, this would generate a PDF
    // For now, we'll create a simple text summary
    const summary = generateTextSummary();
    const blob = new Blob([summary], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `fertilizer-report-${selectedPlant?.name}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleStartOver = () => {
    resetApp();
    navigate('/location-selection');
  };

  const handleViewRecommendations = () => {
    navigate('/recommendations');
  };

  const generateTextSummary = () => {
    return `
================================================================================
FERTILIZER RECOMMENDATION REPORT
================================================================================
Generated: ${new Date().toLocaleString()}
Location: ${municipality}
Crop: ${selectedPlant?.name}

SOIL STATUS
--------------------------------------------------------------------------------
Nitrogen (N):        ${soilData?.nitrogen}
Phosphorus (P):      ${soilData?.phosphorus}
Potassium (K):       ${soilData?.potassium}
Soil pH:             ${soilData?.pH}

RECOMMENDATIONS SUMMARY
--------------------------------------------------------------------------------
Total Products:      ${recommendationSummary?.totalProducts}
High Priority:       ${recommendationSummary?.highPriority}
Medium Priority:     ${recommendationSummary?.mediumPriority}
Estimated Cost:      ₱${recommendationSummary?.estimatedCost?.toLocaleString()} (1 hectare)

FERTILIZER PRODUCTS
--------------------------------------------------------------------------------
${recommendations?.map((rec, i) => `
${i + 1}. ${rec.fertilizer.name} (${rec.fertilizer.formula})
   Priority: ${rec.priority}
   Nutrient: ${rec.nutrient}
   Reason: ${rec.reason}
   Application: ${rec.fertilizer.applicationRate}
   Timing: ${rec.fertilizer.applicationTiming}
   Price: ₱${rec.fertilizer.pricePerBag} per ${rec.fertilizer.bagSize}
`).join('\n') || 'No fertilizers needed - soil is optimal!'}

================================================================================
Generated by SkibiDATA Fertilizer Recommendation System
Using Sentinel-2 Satellite Imagery & Machine Learning
================================================================================
    `.trim();
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-100 via-purple-100 to-pink-100 p-6">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="max-w-4xl mx-auto"
      >
        {/* Celebration Header */}
        <div className="text-center mb-12">
          <motion.div
            initial={{ scale: 0 }}
            animate={{ scale: [0, 1.2, 1] }}
            transition={{ type: 'spring', stiffness: 200, delay: 0.1 }}
            className="inline-block mb-6"
          >
            <span className="text-9xl">🎉</span>
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="text-5xl font-bold text-gray-800 mb-4"
          >
            Analysis Complete!
          </motion.h1>

          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.4 }}
            className="text-xl text-gray-600"
          >
            Your personalized fertilizer plan is ready
          </motion.p>
        </div>

        {/* Summary Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5 }}
            className="bg-white rounded-2xl shadow-xl p-6 text-center"
          >
            <div className="text-4xl mb-3">{selectedPlant?.icon}</div>
            <p className="text-sm text-gray-500 mb-1">Your Crop</p>
            <p className="text-xl font-bold text-gray-800">{selectedPlant?.name}</p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.6 }}
            className="bg-white rounded-2xl shadow-xl p-6 text-center"
          >
            <div className="text-4xl mb-3">📍</div>
            <p className="text-sm text-gray-500 mb-1">Location</p>
            <p className="text-xl font-bold text-gray-800">{municipality}</p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.7 }}
            className="bg-white rounded-2xl shadow-xl p-6 text-center"
          >
            <div className="text-4xl mb-3">💊</div>
            <p className="text-sm text-gray-500 mb-1">Products</p>
            <p className="text-xl font-bold text-gray-800">
              {recommendationSummary?.totalProducts || 0} Recommended
            </p>
          </motion.div>
        </div>

        {/* Action Cards */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.8 }}
          className="space-y-6 mb-12"
        >
          {/* Download Report */}
          <div
            onClick={handleDownloadPDF}
            className="bg-white rounded-2xl shadow-xl p-8 cursor-pointer hover:shadow-2xl transition-all group"
          >
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="text-5xl group-hover:scale-110 transition-transform">📥</div>
                <div>
                  <h3 className="text-2xl font-bold text-gray-800 mb-1">
                    Download Full Report
                  </h3>
                  <p className="text-gray-600">
                    Get a detailed summary of your soil analysis and fertilizer recommendations
                  </p>
                </div>
              </div>
              <div className="text-3xl text-gray-400 group-hover:text-gray-600 group-hover:translate-x-2 transition-all">
                →
              </div>
            </div>
          </div>

          {/* View Recommendations */}
          <div
            onClick={handleViewRecommendations}
            className="bg-white rounded-2xl shadow-xl p-8 cursor-pointer hover:shadow-2xl transition-all group"
          >
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="text-5xl group-hover:scale-110 transition-transform">📋</div>
                <div>
                  <h3 className="text-2xl font-bold text-gray-800 mb-1">
                    Review Recommendations
                  </h3>
                  <p className="text-gray-600">
                    Go back and review your fertilizer plan in detail
                  </p>
                </div>
              </div>
              <div className="text-3xl text-gray-400 group-hover:text-gray-600 group-hover:translate-x-2 transition-all">
                →
              </div>
            </div>
          </div>

          {/* Start New Analysis */}
          <div
            onClick={handleStartOver}
            className="bg-gradient-to-r from-green-500 to-blue-500 rounded-2xl shadow-xl p-8 cursor-pointer hover:shadow-2xl transition-all group"
          >
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="text-5xl group-hover:scale-110 transition-transform">🔄</div>
                <div>
                  <h3 className="text-2xl font-bold text-white mb-1">
                    Analyze Another Crop
                  </h3>
                  <p className="text-white opacity-90">
                    Start a new analysis for a different location or crop type
                  </p>
                </div>
              </div>
              <div className="text-3xl text-white opacity-75 group-hover:opacity-100 group-hover:translate-x-2 transition-all">
                →
              </div>
            </div>
          </div>
        </motion.div>

        {/* Footer */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1 }}
          className="text-center"
        >
          <div className="bg-white rounded-xl shadow-lg p-6">
            <p className="text-sm text-gray-600 mb-2">
              <strong>Thank you for using SkibiDATA!</strong>
            </p>
            <p className="text-xs text-gray-500">
              Powered by Sentinel-2 Satellite Imagery & Machine Learning <br />
              Developed for CAR Highland Vegetable Farmers
            </p>
          </div>
        </motion.div>
      </motion.div>
    </div>
  );
}
